<?php

namespace ContainerHexxosj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MtI1MLdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MtI1MLd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MtI1MLd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'a' => ['privates', 'App\\Repository\\ParticipationRespository', 'getParticipationRespositoryService', true],
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'a' => 'App\\Repository\\ParticipationRespository',
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
