<?php

namespace ContainerHexxosj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JEEpHzzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JEEpHzz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JEEpHzz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'a' => ['privates', 'App\\Repository\\RatingRespository', 'getRatingRespositoryService', true],
        ], [
            'a' => 'App\\Repository\\RatingRespository',
        ]);
    }
}
