<?php

namespace Container2GAWilB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExercice2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.s07JOIL.App\Entity\Exercice' shared service.
     *
     * @return \App\Entity\Exercice
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.s07JOIL": it references class "App\\Entity\\Exercice" but no such service exists.');
    }
}
