<?php

namespace ContainerDSa7eDj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IWM14PCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IWM14PC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IWM14PC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'exercice' => ['privates', '.errored..service_locator.IWM14PC.App\\Entity\\Exercice', NULL, 'Cannot autowire service ".service_locator.IWM14PC": it references class "App\\Entity\\Exercice" but no such service exists.'],
            'exerciceRepository' => ['privates', 'App\\Repository\\ExerciceRepository', 'getExerciceRepositoryService', true],
        ], [
            'exercice' => 'App\\Entity\\Exercice',
            'exerciceRepository' => 'App\\Repository\\ExerciceRepository',
        ]);
    }
}
