<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1eiMvmlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1eiMvml' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1eiMvml'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieProduit' => ['privates', '.errored..service_locator.1eiMvml.App\\Entity\\CategorieProduit', NULL, 'Cannot autowire service ".service_locator.1eiMvml": it references class "App\\Entity\\CategorieProduit" but no such service exists.'],
        ], [
            'categorieProduit' => 'App\\Entity\\CategorieProduit',
        ]);
    }
}
