<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1Ihsr23Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1Ihsr23' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1Ihsr23'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'aliment' => ['privates', '.errored..service_locator.1Ihsr23.App\\Entity\\Aliment', NULL, 'Cannot autowire service ".service_locator.1Ihsr23": it references class "App\\Entity\\Aliment" but no such service exists.'],
        ], [
            'aliment' => 'App\\Entity\\Aliment',
        ]);
    }
}
