<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CL2968TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CL2968T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CL2968T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieLocationRepository' => ['privates', 'App\\Repository\\CategorieLocationRepository', 'getCategorieLocationRepositoryService', true],
        ], [
            'categorieLocationRepository' => 'App\\Repository\\CategorieLocationRepository',
        ]);
    }
}
