<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T_L3DzfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t.L3Dzf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t.L3Dzf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'a' => ['privates', '.errored.Cs9tK1X', NULL, 'Cannot determine controller argument for "App\\Controller\\AcademieController::indexf()": the $a argument is type-hinted with the non-existent class or interface: "App\\Controller\\AbonnementRepository". Did you forget to add a use statement?'],
            'academieRepository' => ['privates', 'App\\Repository\\AcademieRepository', 'getAcademieRepositoryService', true],
        ], [
            'a' => '?',
            'academieRepository' => 'App\\Repository\\AcademieRepository',
        ]);
    }
}
