<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SNyHFuEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sNyHFuE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sNyHFuE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'salleRepository' => ['privates', 'App\\Repository\\SalleRepository', 'getSalleRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'salleRepository' => 'App\\Repository\\SalleRepository',
            'serializer' => '?',
        ]);
    }
}
