<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DEmEQmLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DEmEQmL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DEmEQmL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'routine' => ['privates', '.errored..service_locator.DEmEQmL.App\\Entity\\Routine', NULL, 'Cannot autowire service ".service_locator.DEmEQmL": it references class "App\\Entity\\Routine" but no such service exists.'],
        ], [
            'routine' => 'App\\Entity\\Routine',
        ]);
    }
}
