<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4P9JRqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4P9_JRq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4P9_JRq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieLocationRepository' => ['privates', 'App\\Repository\\CategorieLocationRepository', 'getCategorieLocationRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'categorieLocationRepository' => 'App\\Repository\\CategorieLocationRepository',
            'serializer' => '?',
        ]);
    }
}
