<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2exieU2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2exieU2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2exieU2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cours' => ['privates', '.errored..service_locator.2exieU2.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.2exieU2": it references class "App\\Entity\\Cours" but no such service exists.'],
        ], [
            'cours' => 'App\\Entity\\Cours',
        ]);
    }
}
