<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cyo_JlbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cyo.Jlb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cyo.Jlb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alimentRepository' => ['privates', 'App\\Repository\\AlimentRepository', 'getAlimentRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'objectifRepository' => ['privates', 'App\\Repository\\ObjectifRepository', 'getObjectifRepositoryService', true],
            'routineRepository' => ['privates', 'App\\Repository\\RoutineRepository', 'getRoutineRepositoryService', true],
        ], [
            'alimentRepository' => 'App\\Repository\\AlimentRepository',
            'mailer' => '?',
            'objectifRepository' => 'App\\Repository\\ObjectifRepository',
            'routineRepository' => 'App\\Repository\\RoutineRepository',
        ]);
    }
}
