<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LeuA80eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LeuA80e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LeuA80e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'espace' => ['privates', '.errored..service_locator.LeuA80e.App\\Entity\\Espace', NULL, 'Cannot autowire service ".service_locator.LeuA80e": it references class "App\\Entity\\Espace" but no such service exists.'],
            'espaceRepository' => ['privates', 'App\\Repository\\EspaceRepository', 'getEspaceRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'espace' => 'App\\Entity\\Espace',
            'espaceRepository' => 'App\\Repository\\EspaceRepository',
            'slugger' => '?',
        ]);
    }
}
