<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_US0TFg0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.US0TFg0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.US0TFg0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'espace' => ['privates', '.errored..service_locator.US0TFg0.App\\Entity\\Espace', NULL, 'Cannot autowire service ".service_locator.US0TFg0": it references class "App\\Entity\\Espace" but no such service exists.'],
        ], [
            'espace' => 'App\\Entity\\Espace',
        ]);
    }
}
