<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_9AHrITService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.9AHr_IT' shared service.
     *
     * @return \App\Controller\AbonnementRespository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\AcademieController::enlever()": the $b argument is type-hinted with the non-existent class or interface: "App\\Controller\\AbonnementRespository". Did you forget to add a use statement?');
    }
}
