<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OwktN9vService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OwktN9v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OwktN9v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'academie' => ['privates', '.errored..service_locator.OwktN9v.App\\Entity\\Academie', NULL, 'Cannot autowire service ".service_locator.OwktN9v": it references class "App\\Entity\\Academie" but no such service exists.'],
        ], [
            'academie' => 'App\\Entity\\Academie',
        ]);
    }
}
