<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PkVeAM_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PkVeAM.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PkVeAM.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'salle' => ['privates', '.errored..service_locator.PkVeAM..App\\Entity\\Salle', NULL, 'Cannot autowire service ".service_locator.PkVeAM.": it references class "App\\Entity\\Salle" but no such service exists.'],
        ], [
            'salle' => 'App\\Entity\\Salle',
        ]);
    }
}
