<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G0GMtaCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G0GMtaC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G0GMtaC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cours' => ['privates', '.errored..service_locator.G0GMtaC.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.G0GMtaC": it references class "App\\Entity\\Cours" but no such service exists.'],
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
        ], [
            'cours' => 'App\\Entity\\Cours',
            'coursRepository' => 'App\\Repository\\CoursRepository',
        ]);
    }
}
