<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DGy8tCHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dGy8tCH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dGy8tCH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'academie' => ['privates', '.errored..service_locator.dGy8tCH.App\\Entity\\Academie', NULL, 'Cannot autowire service ".service_locator.dGy8tCH": it references class "App\\Entity\\Academie" but no such service exists.'],
            'academieRepository' => ['privates', 'App\\Repository\\AcademieRepository', 'getAcademieRepositoryService', true],
            'salleRepository' => ['privates', 'App\\Repository\\SalleRepository', 'getSalleRepositoryService', true],
        ], [
            'academie' => 'App\\Entity\\Academie',
            'academieRepository' => 'App\\Repository\\AcademieRepository',
            'salleRepository' => 'App\\Repository\\SalleRepository',
        ]);
    }
}
