<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5r9DV4EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5r9DV4E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5r9DV4E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieProduitRepository' => ['privates', 'App\\Repository\\CategorieProduitRepository', 'getCategorieProduitRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'categorieProduitRepository' => 'App\\Repository\\CategorieProduitRepository',
            'paginator' => '?',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
