<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Cs9tK1XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Cs9tK1X' shared service.
     *
     * @return \App\Controller\AbonnementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\AcademieController::indexf()": the $a argument is type-hinted with the non-existent class or interface: "App\\Controller\\AbonnementRepository". Did you forget to add a use statement?');
    }
}
