<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CjshCkxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cjshCkx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cjshCkx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'objectif' => ['privates', '.errored..service_locator.cjshCkx.App\\Entity\\Objectif', NULL, 'Cannot autowire service ".service_locator.cjshCkx": it references class "App\\Entity\\Objectif" but no such service exists.'],
        ], [
            'objectif' => 'App\\Entity\\Objectif',
        ]);
    }
}
