<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6My0nZkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6My0nZk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6My0nZk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'b' => ['privates', '.errored.9AHr_IT', NULL, 'Cannot determine controller argument for "App\\Controller\\AcademieController::enlever()": the $b argument is type-hinted with the non-existent class or interface: "App\\Controller\\AbonnementRespository". Did you forget to add a use statement?'],
        ], [
            'b' => '?',
        ]);
    }
}
