<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8lKmvpoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8lKmvpo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8lKmvpo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieLocation' => ['privates', '.errored..service_locator.8lKmvpo.App\\Entity\\CategorieLocation', NULL, 'Cannot autowire service ".service_locator.8lKmvpo": it references class "App\\Entity\\CategorieLocation" but no such service exists.'],
            'categorieLocationRepository' => ['privates', 'App\\Repository\\CategorieLocationRepository', 'getCategorieLocationRepositoryService', true],
        ], [
            'categorieLocation' => 'App\\Entity\\CategorieLocation',
            'categorieLocationRepository' => 'App\\Repository\\CategorieLocationRepository',
        ]);
    }
}
