<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VLW4NyOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VLW4NyO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VLW4NyO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'espaceRepository' => ['privates', 'App\\Repository\\EspaceRepository', 'getEspaceRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'espaceRepository' => 'App\\Repository\\EspaceRepository',
            'mailer' => '?',
            'slugger' => '?',
        ]);
    }
}
