<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_05mgaorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.05mgaor' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.05mgaor'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'academieRepository' => ['privates', 'App\\Repository\\AcademieRepository', 'getAcademieRepositoryService', true],
            'serializerInterface' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'academieRepository' => 'App\\Repository\\AcademieRepository',
            'serializerInterface' => '?',
        ]);
    }
}
