<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KWcQxtBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KWcQxtB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KWcQxtB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'aliment' => ['privates', '.errored..service_locator.KWcQxtB.App\\Entity\\Aliment', NULL, 'Cannot autowire service ".service_locator.KWcQxtB": it references class "App\\Entity\\Aliment" but no such service exists.'],
            'alimentRepository' => ['privates', 'App\\Repository\\AlimentRepository', 'getAlimentRepositoryService', true],
        ], [
            'aliment' => 'App\\Entity\\Aliment',
            'alimentRepository' => 'App\\Repository\\AlimentRepository',
        ]);
    }
}
