<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcademie2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OwktN9v.App\Entity\Academie' shared service.
     *
     * @return \App\Entity\Academie
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.OwktN9v": it references class "App\\Entity\\Academie" but no such service exists.');
    }
}
