<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlimentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1Ihsr23.App\Entity\Aliment' shared service.
     *
     * @return \App\Entity\Aliment
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1Ihsr23": it references class "App\\Entity\\Aliment" but no such service exists.');
    }
}
