<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieProduit2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NgpnsuM.App\Entity\CategorieProduit' shared service.
     *
     * @return \App\Entity\CategorieProduit
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.NgpnsuM": it references class "App\\Entity\\CategorieProduit" but no such service exists.');
    }
}
