<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieLocation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8lKmvpo.App\Entity\CategorieLocation' shared service.
     *
     * @return \App\Entity\CategorieLocation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8lKmvpo": it references class "App\\Entity\\CategorieLocation" but no such service exists.');
    }
}
