<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEspace2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LeuA80e.App\Entity\Espace' shared service.
     *
     * @return \App\Entity\Espace
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.LeuA80e": it references class "App\\Entity\\Espace" but no such service exists.');
    }
}
