<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoutine2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.y.bhuG8.App\Entity\Routine' shared service.
     *
     * @return \App\Entity\Routine
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.y.bhuG8": it references class "App\\Entity\\Routine" but no such service exists.');
    }
}
