<?php

namespace ContainerBxqBX5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalle2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HvUaTXU.App\Entity\Salle' shared service.
     *
     * @return \App\Entity\Salle
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HvUaTXU": it references class "App\\Entity\\Salle" but no such service exists.');
    }
}
