<?php

namespace ContainerTTRhG3X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M5jG2ZvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m5jG2Zv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m5jG2Zv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.errored..service_locator.m5jG2Zv.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.m5jG2Zv": it references class "App\\Entity\\Client" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'client' => 'App\\Entity\\Client',
            'entityManager' => '?',
            'userPasswordHasher' => '?',
        ]);
    }
}
