<?php

namespace ContainerTTRhG3X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._OplB_o.App\Entity\Client' shared service.
     *
     * @return \App\Entity\Client
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._OplB_o": it references class "App\\Entity\\Client" but no such service exists.');
    }
}
