<?php

namespace Container0pTv5Td;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A5ODqIiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A5ODqIi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A5ODqIi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'a' => ['privates', '.errored.6ctd0PL', NULL, 'Cannot determine controller argument for "App\\Controller\\EvenementController::indexFront()": the $a argument is type-hinted with the non-existent class or interface: "App\\Repository\\ParticipationRespository".'],
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'a' => '?',
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
