<?php

namespace Container0pTv5Td;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WS6MSrRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wS6MSrR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wS6MSrR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'b' => ['privates', '.errored.NT2K50g', NULL, 'Cannot determine controller argument for "App\\Controller\\EvenementController::imparticiper()": the $b argument is type-hinted with the non-existent class or interface: "App\\Repository\\ParticipationRespository".'],
        ], [
            'b' => '?',
        ]);
    }
}
