<?php

namespace Container0pTv5Td;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClient3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.m5jG2Zv.App\Entity\Client' shared service.
     *
     * @return \App\Entity\Client
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.m5jG2Zv": it references class "App\\Entity\\Client" but no such service exists.');
    }
}
