<?php

namespace Container0pTv5Td;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingRespositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JEEpHzz.App\Repository\RatingRespository' shared service.
     *
     * @return \App\Repository\RatingRespository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.JEEpHzz": it references class "App\\Repository\\RatingRespository" but no such service exists.');
    }
}
