<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2GAWilB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2GAWilB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2GAWilB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2GAWilB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2GAWilB\App_KernelDevDebugContainer([
    'container.build_hash' => '2GAWilB',
    'container.build_id' => 'cff1a57e',
    'container.build_time' => 1677092178,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2GAWilB');
